spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/freepdb1

spring.datasource.username=myuser
spring.datasource.password=mypassword

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=9a4f2c8d3b7a1e6f4g5h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z
jwt.lifetime=86400000